global:

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 10h
  receiver: discord
  routes:
    - matchers:
        - alertname="accounts_firing"
      receiver: discord
receivers:
  - name: discord
    discord_configs:
      # IT DOESN'T SUPPORT TEMPLATING FOR SECURITY REASONS YOU NEED TO COME HERE AND SET. READ docker-compose
      # https://support.discord.com/hc/en-us/articles/228383668-Intro-to-Webhooks
      - webhook_url: https://support.discord.com/hc/en-us/articles/228383668-Intro-to-Webhooks
