version: '3'
services:
  nginx-server:
    image: nginx
    ports:
      - '3000:3000'
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - backend
      - frontend
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile.dev
    ports:
      - '3001:3000'
    depends_on:
      - backend
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile.dev
    ports:
      - '3002:3000'
    restart: always
    environment:
      MONGO_URI: mongodb://mongodb:27017/accounts
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
volumes:
  mongodb_data_container:
