version: '3'
services:
  nginx-server:
    image: nginx
    ports:
      - '3000:3000'
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - backend
      - frontend
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile.dev
    ports:
      - '3001:3000'
    depends_on:
      - backend
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile.dev
    ports:
      - '3002:3000'
    restart: always
    environment:
      - MONGO_URI=mongodb://mongodb:27017/accounts
    depends_on:
      - mongodb

  backend_monitor:
    build:
      context: ../backendMonitor
      dockerfile: Dockerfile.dev
    ports:
      - '3003:3000'
    environment:
      - MONGO_URI=mongodb://mongodb:27017/accounts
      - CHAIN_URI=wss://westend-rpc.polkadot.io
      - POOLING_FREQUENCY=3000
    restart: always
    volumes:
      - ../backendMonitor/addresses.csv:/app/addresses.csv
    depends_on:
      - mongodb

  mongodb_query_exporter:
    build:
      context: ../mongoExporter
    ports:
      - '9412:9412'
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
    restart: always
    depends_on:
      - mongodb

  # IT DOESN'T SUPPORT TEMPLATING FOR SECURITY REASONS YOU NEED TO COME HERE AND SET.
  # https://support.discord.com/hc/en-us/articles/228383668-Intro-to-Webhooks
  alert_manager:
    build:
      context: ../alertManager
    entrypoint:
      - sh
      - -euc
      - |
        # mkdir -p /etc/alertmanager
        echo "$${ALERTMANAGER_CONFIG}" > /etc/alertmanager/alertmanager.yml
        /bin/alertmanager --config.file=/etc/alertmanager/alertmanager.yml --storage.path=/alertmanager
    ports:
      - '9093:9093'
    environment:
      ALERTMANAGER_CONFIG: |
        global:

        route:
          group_by: ['alertname']
          group_wait: 10s
          group_interval: 10s
          repeat_interval: 10h
          receiver: discord
          routes:
            - matchers:
                - alertname='accounts_firing'
              receiver: discord
        receivers:
          - name: discord
            discord_configs:
              - webhook_url: 'https://support.discord.com/hc/en-us/articles/228383668-Intro-to-Webhooks'
    depends_on:
      - mongodb_query_exporter

  prometheus:
    build:
      context: ../prometheus
    entrypoint:
      - sh
      - -euc
      - |
        # mkdir -p /etc/prometheus
        echo "$${PROMETHEUS_CONFIG}" > /etc/prometheus/prometheus-config.yml
        /bin/prometheus --config.file=/etc/prometheus/prometheus-config.yml
    ports:
      - '9090:9090'
    environment:
      PROMETHEUS_CONFIG: |
        global:
          scrape_interval: 2s # Set the scrape interval to every 2 seconds. Default is every 1 minute.
          evaluation_interval: 2s # Evaluate rules every 2 seconds. The default is every 1 minute.

        rule_files:
          - rules.yml

        alerting:
          alertmanagers:
            - static_configs:
                - targets:
                    # Alertmanager's default port is 9093
                    - alert_manager:9093

        scrape_configs:
          - job_name: 'mongodb_exporter'
            static_configs:
              - targets: ['mongodb_query_exporter:9412']
    depends_on:
      - alert_manager

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
volumes:
  mongodb_data_container:
