apiVersion: v1
kind: Pod
metadata:
  name: prometheus-alertmanager-pod
spec:
  containers:
    - name: prometheus-container
      image: armando1514/prometheus
      ports:
        - containerPort: 9090
      env:
        - name: PROMETHEUS_CONFIG
          value: |
            global:
              scrape_interval: 2s
              evaluation_interval: 2s

            rule_files:
              - rules.yml

            alerting:
              alertmanagers:
                - static_configs:
                    - targets:
                        - localhost:9093

            scrape_configs:
              - job_name: 'mongodb_exporter'
                static_configs:
                  - targets: ['mongodb-query-exporter:9412']
      command:
        - '/bin/sh'
        - '-c'
        - |
          # mkdir -p /etc/prometheus
          echo "$${PROMETHEUS_CONFIG}" > /etc/prometheus/prometheus-config.yml
          /bin/prometheus --config.file=/etc/prometheus/prometheus-config.yml

    - name: alert-manager-container
      image: prom/alertmanager:latest
      ports:
        - containerPort: 9093
      env:
        - name: ALERTMANAGER_CONFIG
          value: |
            global:

            route:
              group_by: ['alertname']
              group_wait: 10s
              group_interval: 10s
              repeat_interval: 10h
              receiver: discord
              routes:
                - matchers:
                    - alertname='accounts_firing'
                  receiver: discord
            receivers:
              - name: discord
                discord_configs:
                  - webhook_url: 'https://support.discord.com/hc/en-us/articles/228383668-Intro-to-Webhooks'
      command:
        - '/bin/sh'
        - '-c'
        - |
          # mkdir -p /etc/alertmanager
          echo "$${ALERTMANAGER_CONFIG}" > /etc/alertmanager/alertmanager-config.yml
          /bin/alertmanager --config.file=/etc/alertmanager/alertmanager-config.yml
