version: 3.0
bind: 0.0.0.0:9412
metricsPath: /metrics
log:
  encoding: json
  level: info
  development: false
  disableCaller: false
global:
  queryTimeout: '10s'
  maxConnection: 3
  defaultCache: 0
servers:
  - name: main
    uri: ${MONGO_URI}
aggregations:
  database: accounts
  collection: reported_accounts
  servers: [main]
  metrics:
    - name: firing_reported_accounts
      type: gauge
      help: 'Count of documents grouped by address and blockNumber'
      value: count
      labels: [address, blockNumber]
  mode: pull
  pipeline: |
    [
      {
        "$group": {
          "_id": {
            "address": { "$toString": "$address" },
            "blockNumber": { "$toString": "$blockNumber" }
          },
          "count": { "$sum": 1 }
        }
      },
      {
        "$project": {
          "_id": 0,
          "address": "$_id.address",
          "blockNumber": "$_id.blockNumber",
          "count": "$count"
        }
      }
    ]
