name: Docker backend tests

on:
  push:
    branches: [ "main", "component/backend-monitor" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build -t my-dev-image -f backendMonitor/Dockerfile.test backendMonitor
        docker run --rm my-dev-image
